[platformio]
default_envs = maker_badge_esp32s2

[env]
platform = espressif32
board = esp32-s2-saola-1
framework = arduino
monitor_speed = 115200
board_build.partitions = partitions.csv

lib_deps =
  zinggjm/GxEPD2@^1.6.9
  kitesurfer1404/WS2812FX@^1.4.6

build_flags =
  -D ENABLE_GxEPD2_GFX=0
  -D ARDUINO_USB_CDC_ON_BOOT=1

; For rev. A badges with the UC8151D / GDEW0213T5D display, uncomment:
;  -D MAKER_BADGE_REV_A_DISPLAY=1

[env:maker_badge_esp32s2]

[env:maker_badge_debug]
build_flags =
  ${env.build_flags}
  -D SLEEP_AFTER_ACTION=0
  -D IDLE_SLEEP_TIMEOUT_MS=15000UL
